export const PERMISSIONS = {
  CREATE_USER: "CREATE_USER",
  READ_USER: "READ_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",

  CREATE_ROLE: "CREATE_ROLE",
  READ_ROLE: "READ_ROLE",
  UPDATE_ROLE: "UPDATE_ROLE",
  DELETE_ROLE: "DELETE_ROLE",

  CREATE_SITE: "CREATE_SITE",
  READ_SITE: "READ_SITE",
  UPDATE_SITE: "UPDATE_SITE",
  DELETE_SITE: "DELETE_SITE",
};
